#!/bin/bash

# Dotfiles and bootstrap installer

set -e
trap on_error SIGTERM

e='\033'
RESET="${e}[0m"
BOLD="${e}[1m"
CYAN="${e}[0;96m"
RED="${e}[0;91m"
YELLOW="${e}[0;93m"
GREEN="${e}[0;92m"

_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Success reporter
info() {
    echo -e "${CYAN}${*}${RESET}"
}

# Error reporter
error() {
    echo -e "${RED}${*}${RESET}"
}

# Success reporter
success() {
    echo -e "${GREEN}${*}${RESET}"
}

# End section
finish() {
    success "Done!"
    echo
    sleep 1
}

# Set directory
export DOTFILES=${1:-"$HOME/.dotfiles"}
GITHUB_REPO_URL_BASE="https://github.com/kylebrantley/.dotfiles"
HOMEBREW_INSTALLER_URL="https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"
LUNARVIM_INSTALLER_URL="https://raw.githubusercontent.com/lunarvim/lunarvim/fc6873809934917b470bff1b072171879899a36b/utils/installer/install.sh"

install_homebrew() {
    info "Trying to detect installed Homebrew..."

    if ! _exists brew; then
        echo "Seems like you don't have Homebrew installed!"
        read -p "Do you agree to proceed with Homebrew installation? [y/N] " -n 1 answer
        echo
        if [ "${answer}" != "y" ]; then
            exit 1
        fi

        info "Installing Homebrew..."
        bash -c "$(curl -fsSL ${HOMEBREW_INSTALLER_URL})"

        export PATH="/opt/homebrew/bin:$PATH"
        export PATH="/opt/homebrew/sbin:$PATH"
    else
        success "You already have Homebrew installed. Skipping..."
        export PATH="/opt/homebrew/bin:$PATH"
        export PATH="/opt/homebrew/sbin:$PATH"
    fi

    finish
}

install_brew_packages() {
    if [ "$(uname)" != "Darwin" ]; then
        return
    fi

    info "Installing software..."

    cd "$DOTFILES"

    # Homebrew Bundle
    if _exists brew; then
        brew bundle
    else
        error "Error: Brew is not available"
    fi

    cd -

    finish
}

install_lunarvim() {
    if ! _exists lvim; then
        # Using the latest and greatest lvim version
        LV_BRANCH='release-1.2/neovim-0.8'
        bash -c "$(curl -s ${LUNARVIM_INSTALLER_URL})"
    else
        success "Lunarvim is already installed"
    fi

    finish
}

on_finish() {
    echo
    success "Setup was successfull!"
    echo
}

on_error() {
    echo
    error "Something broke"
    echo
    exit 1
}

main() {
    install_homebrew "$*"
    install_brew_packages "$*"
    install_lunarvim "$*"
    on_finish "$*"
}

main "$*"
