require "user.plugins"
require "user.impatient"

require "user.options"
require "user.keymaps"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.nvim-tree"
require "user.lualine"
require "user.comment"
require "user.autocommands"
